version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@3.0.0

jobs:
  test-playwright:
    docker:
      - image: cimg/node:lts
    environment:
      CI_COMMIT_SHORT_SHA: $CIRCLE_SHA1
    steps:
      - checkout
      - saucectl/saucectl-run

workflows:
  version: 2
  default_workflow:
    jobs:
      - test-playwright
